---
- name: Configure the local timezone to UTC
  hosts: local
  tasks:

    - name: Update timezone to Etc/UTC
      copy:
        content: "Etc/UTC\n"
        dest: /etc/timezone
      register: timezone

    - name: Reconfigure timezone data
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed

- name: Create a new user named grader and grant this user sudo permissions
  hosts: local
  tasks:
    - name: Setup user grader
      user:
        name: grader

    - name: Make sure grader can sudo
      lineinfile:
        dest: /etc/sudoers.d/grader
        create: yes
        mode: 0400
        owner: root
        group: root
        state: present
        regexp: "^%grader"
        line: "%grader ALL=(ALL) NOPASSWD:ALL"
        validate: visudo --quiet --check --file=%s

