---
- name: Perform Basic Configuration
  hosts: local
  tasks:
    - name: Setup user grader
      user:
        name: grader

    - name: Make sure grader can sudo
      lineinfile:
        dest: /etc/sudoers.d/grader
        create: yes
        mode: 0400
        owner: root
        group: root
        state: present
        regexp: "^%grader"
        line: "%grader ALL=(ALL) NOPASSWD:ALL"
        validate: visudo --quiet --check --file=%s

    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: safe

    - name: Update timezone to Etc/UTC
      copy:
        content: "Etc/UTC\n"
        dest: /etc/timezone
      register: timezone

    - name: Reconfigure timezone data
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed

- name: Secure Server
  hosts: local
  tasks:
      # TODO: Change SSH port from 22 to 2200
      #       This will probably need a `vagrant reload`
      #- name: Change SSH port from 22 to 2200
      #  lineinfile:
      #    dest: /etc/ssh/sshd_config
      #    regexp: "^Port"
      #    line: "Port 2200"
      #    state: present
      #  notify: Restart SSH

      - name: Enable UFW and deny everything
        ufw:
          state: enabled
          policy: deny
      - name: Allow SSH traffic
        ufw:
          rule: allow
          # TODO: Change SSH port from 22 to 2200
          port: 22
          proto: tcp
      - name: Allow HTTP traffic
        ufw:
          rule: allow
          port: 80
          proto: tcp
      - name: Allow NTP traffic
        ufw:
          rule: allow
          port: 123
          proto: tcp
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

- name: Install Application
  hosts: local
  tasks:

    - name: Install Apache with mod_wsgi
      apt:
        name:
          - apache2
          - libapache2-mod-wsgi
        update_cache: yes
        state: latest

    - name: Enable mod_wsgi
      apache2_module:
        name: wsgi
        state: present
      notify: Restart Apache2

    - name: Install PostgreSQL
      apt:
        name: postgresql
        update_cache: yes
        state: latest

    - name: Install packages needed for Catalog App
      apt:
        name:
          - python-flask
          - python-pip
          - python-psycopg2
          - python-sqlalchemy

    - name: Install PyPI package oauth2client
      pip:
        name: oauth2client
        state: present

    - name: Install PyPI package requests
      pip:
        name: requests
        state: present


    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Catalog App project
      git:
        repo: https://github.com/swesterveld/udacity-nd004-p3-item-catalog.git
        dest: /var/www/catalog
        update: no

  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
