---
- name: Prepare host for deployments by deploy user only
  hosts: udacity_p5
  vars:
    deploy_user_name: deploy
    deploy_public_key: ~/.ssh/id_rsa_ansible.pub
    ssh_port: 22

  tasks:
    - name: the deploy user exists
      user:
        name: "{{ deploy_user_name }}"
        append: yes
        shell: /bin/bash

    - name: the deploy user has authorized keys
      authorized_key:
        user: "{{ deploy_user_name }}"
        key: "{{ lookup('file', deploy_public_key ) }}"

    - name: the deploy user can sudo
      lineinfile:
        dest: /etc/sudoers.d/deploy
        create: yes
        mode: 0400
        owner: root
        group: root
        state: present
        regexp: "^%{{ deploy_user_name }}"
        line: "%{{ deploy_user_name }} ALL=(ALL) NOPASSWD:ALL"
        validate: visudo --quiet --check --file=%s

    - name: root login is disabled
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: SSH restart

    - name: password authentication is disabled
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: SSH restart

    - name: SSH is listening on port 2200
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^Port"
        line: "Port 2200"
        state: present
      notify: SSH restart

    - name: UFW is installed
      apt:
        name: ufw

    - name: UFW is enabled with policy to deny by default
      ufw:
        state: enabled
        policy: deny

    - name: port 2200 (for SSH) is open in UFW
      ufw:
        rule: allow
        port: 2200
        proto: tcp

  handlers:
    - name: SSH restart
      service:
        name: ssh
        state: restarted
